### ISSUE TITLE
Importing rfc3987 causes SyntaxError with `-W error`

### ISSUE THREAD

**Issue by blueyed** [dgerber/rfc3987#14]
When using `python -W error` to turn warnings into errors, importing `rfc3987` causes a SyntaxError:

```
% python -W error
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
Using histfile /home/user/.python_history (via pythonrc)
>>> import rfc3987
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "…/pyenv/tmp-system-django-rest-framework-jwt-refresh-token-2kQKmV/lib/python3.6/site-packages/rfc3987.py", line 357, in <module>
    in format_patterns().items())
  File "…/pyenv/tmp-system-django-rest-framework-jwt-refresh-token-2kQKmV/lib/python3.6/site-packages/rfc3987.py", line 356, in <genexpr>
    upatterns_no_names = dict((k, _interpret_unicode_escapes(v)) for k,v
  File "…/pyenv/tmp-system-django-rest-framework-jwt-refresh-token-2kQKmV/lib/python3.6/site-packages/rfc3987.py", line 350, in _interpret_unicode_escapes
    return _ast.literal_eval(_unicode_escapes_tpl.format(string))
  File "/usr/lib64/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
SyntaxError: invalid escape sequence \]
```

```
(Pdb++) (source, filename, mode, PyCF_ONLY_AST)
('"""[:/?#[\\]@]"""', '<unknown>', 'eval', 1024)
```

**Comment by blueyed** [comment]
This is due to a DeprecationWarning being converted to a SyntaxError:
https://github.com/python/cpython/blob/0febc053736112d7bb9081742b3ac0ece7b973e7/Python/ast.c#L4152-L4182

It can be ignored using `-W error -W 'ignore:invalid escape sequence:DeprecationWarning'`, and seen already using `-W all`:
```
% python -W all -c "compile('\"\\[\"', '', 'eval')"  
<string>:1: DeprecationWarning: invalid escape sequence \[
:1: DeprecationWarning: invalid escape sequence \[
```

**Comment by dgerber** [comment]
Thanks for reporting. It'll be fixed in the next release with `.decode('unicode-escape')`. The `r''` syntax would not interpret those `\u....` escapes at all.

The deprecation is [documented here](https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior)

**Comment by dgerber** [comment]
https://github.com/dgerber/rfc3987/pull/16
